# Copyright (c) Microsoft Corporation and contributors. All rights reserved.
# Licensed under the MIT License.

# test-sharedstring-stress pipeline

name: $(Build.BuildId)

trigger: none
pr: none

resources:
  pipelines:
  - pipeline: client   # Name of the pipeline resource
    source: Build - client packages
    trigger:
      branches:
      - release/*
      - main
      - next

variables:
- name: testWorkspace
  value: $(Pipeline.Workspace)/test

stages:
  - stage:
    displayName:  Stress tests - SharedString
    dependsOn: []
    jobs:
    - template: templates/include-test-real-service.yml
      parameters:
        poolBuild: Small # TODO: Revisit pool size / general machine choices
        testPackage: "@fluid-internal/test-sharedstring-stress"
        testWorkspace: ${{ variables.testWorkspace }}
        timeoutInMinutes: 120
        testCommand: test:mocha
        env:
          TEST_COUNT: 5
